"""Beta estimation, shrinkage, and dispersion calibration.

Betas are planted in simulated return series, so the regression is asked to
recover a number it was not told — and the shrinkage rules are tested for the
property that motivates them: that a NOISY estimate moves toward the market and
a PRECISE one does not.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from _lib import riskmodel as R


def make_returns(beta=1.2, n=500, idiosyncratic=0.01, market_vol=0.011, seed=3):
    """A stock generated by the market model with a known beta."""
    rng = np.random.default_rng(seed)
    market = rng.normal(0.0004, market_vol, n)
    stock = beta * market + rng.normal(0.0, idiosyncratic, n)
    return stock, market


def price_frame(stock_returns, index_returns, seed=0):
    """Turn return series into the OHLCV frame estimate_beta expects."""
    index = pd.bdate_range("2023-01-02", periods=len(stock_returns))
    close = 100 * np.exp(np.cumsum(stock_returns))
    frame = pd.DataFrame({"Close": close}, index=index)
    market = pd.Series(index_returns, index=index)
    return frame, market


# --------------------------------------------------------------------------- #
# OLS
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("true_beta", [0.4, 0.8, 1.0, 1.6, 2.2])
def test_ols_recovers_the_planted_beta(true_beta):
    stock, market = make_returns(beta=true_beta, n=1500, seed=7)
    beta, stderr, r_squared = R.ols_beta(stock, market)
    assert beta == pytest.approx(true_beta, abs=4 * stderr)
    assert 0.0 <= r_squared <= 1.0


def test_standard_error_grows_with_idiosyncratic_noise():
    """The error bar has to mean something for Vasicek to be worth using."""
    clean = R.ols_beta(*make_returns(idiosyncratic=0.002, seed=1))[1]
    noisy = R.ols_beta(*make_returns(idiosyncratic=0.050, seed=1))[1]
    assert noisy > clean * 5


def test_ols_returns_nan_on_degenerate_input():
    beta, _stderr, _r2 = R.ols_beta(np.array([0.01, 0.02]), np.array([0.0, 0.0]))
    assert np.isnan(beta)


# --------------------------------------------------------------------------- #
# Shrinkage
# --------------------------------------------------------------------------- #
def test_blume_matches_the_bloomberg_rule():
    """Blume's coefficients are ~1/3 + 2/3*beta, which is 'adjusted beta'."""
    assert R.blume_adjust(1.0) == pytest.approx(1.02, abs=0.02)
    assert R.blume_adjust(2.0) == pytest.approx(1.697, abs=0.01)
    assert R.blume_adjust(0.0) == pytest.approx(0.343, abs=0.01)


def test_blume_always_moves_toward_one():
    for beta in (0.2, 0.5, 1.5, 2.5, 3.0):
        adjusted = R.blume_adjust(beta)
        assert abs(adjusted - 1.0) < abs(beta - 1.0)


def test_vasicek_barely_moves_a_precise_estimate():
    adjusted, weight = R.vasicek_adjust(1.8, stderr=0.05)
    assert weight < 0.02
    assert adjusted == pytest.approx(1.8, abs=0.02)


def test_vasicek_collapses_a_hopeless_estimate_toward_the_market():
    """The IDX small-cap case: a beta whose error bar swamps the estimate."""
    adjusted, weight = R.vasicek_adjust(2.4, stderr=1.5)
    assert weight > 0.85
    assert adjusted == pytest.approx(1.0, abs=0.25)


def test_vasicek_shrinkage_is_monotonic_in_the_standard_error():
    weights = [R.vasicek_adjust(1.8, stderr=se)[1] for se in (0.05, 0.2, 0.5, 1.0, 2.0)]
    assert weights == sorted(weights)


def test_vasicek_is_better_than_a_fixed_clip_on_noisy_betas():
    """The argument for replacing clip_beta, made quantitatively.

    Many stocks whose TRUE beta is 1.0 but whose estimates are noisy: Vasicek's
    adjusted betas should sit closer to the truth than a [0.4, 2.5] clip, which
    passes almost every noisy estimate through untouched.
    """
    rng = np.random.default_rng(0)
    true_beta = 1.0
    clip_error, vasicek_error = [], []
    for _ in range(300):
        estimate = true_beta + rng.normal(0.0, 0.6)      # a noisy measurement
        stderr = 0.6
        clipped = float(np.clip(estimate, 0.4, 2.5))
        adjusted, _ = R.vasicek_adjust(estimate, stderr)
        clip_error.append((clipped - true_beta) ** 2)
        vasicek_error.append((adjusted - true_beta) ** 2)

    assert np.mean(vasicek_error) < np.mean(clip_error), (
        f"Vasicek MSE {np.mean(vasicek_error):.4f} did not beat "
        f"clip MSE {np.mean(clip_error):.4f}"
    )


# --------------------------------------------------------------------------- #
# estimate_beta end to end
# --------------------------------------------------------------------------- #
def test_estimate_beta_recovers_and_reports_its_own_quality(monkeypatch):
    stock, market = make_returns(beta=1.5, n=600, idiosyncratic=0.004, seed=11)
    frame, market_series = price_frame(stock, market)
    monkeypatch.setattr(R, "_index_returns", lambda *a, **k: market_series)

    result = R.estimate_beta(frame, "US")
    assert result.method == "vasicek"
    assert result.raw == pytest.approx(1.5, abs=0.1)
    assert result.observations > 500
    assert 0.0 < result.r_squared <= 1.0
    assert result.prior_weight < 0.1          # a precise estimate barely shrinks
    assert result.index_symbol == "^GSPC"


def test_estimate_beta_falls_back_when_the_index_is_unavailable(monkeypatch):
    monkeypatch.setattr(R, "_index_returns", lambda *a, **k: None)
    result = R.estimate_beta(pd.DataFrame({"Close": [1.0, 2.0]}), "ID", fallback_beta=1.9)
    assert result.method == "blume-fallback"
    assert result.adjusted == pytest.approx(R.blume_adjust(1.9))
    assert result.index_symbol == "^JKSE"
    assert result.notes


def test_estimate_beta_refuses_a_short_overlap(monkeypatch):
    stock, market = make_returns(n=20, seed=2)
    frame, market_series = price_frame(stock, market)
    monkeypatch.setattr(R, "_index_returns", lambda *a, **k: market_series)
    result = R.estimate_beta(frame, "US", fallback_beta=1.1)
    assert result.method == "blume-fallback"
    assert "overlapping" in " ".join(result.notes)


def test_beta_estimate_serialises_json_safely(monkeypatch):
    import json
    from _lib.jsonsafe import clean

    monkeypatch.setattr(R, "_index_returns", lambda *a, **k: None)
    payload = R.estimate_beta(pd.DataFrame(), "US", fallback_beta=None).as_dict()
    json.dumps(clean(payload), allow_nan=False)


# --------------------------------------------------------------------------- #
# Growth dispersion
# --------------------------------------------------------------------------- #
def test_growth_dispersion_falls_back_to_the_prior_on_thin_history():
    result = R.shrunk_growth_volatility([100.0])
    assert result["source"] == "prior only"
    assert result["sd"] == pytest.approx(R.PRIOR_GROWTH_SD)
    assert result["priorWeight"] == 1.0


def test_a_stable_company_narrows_the_dispersion():
    """Steady 5% growth every year should pull the estimate below the prior."""
    steady = [100 * 1.05 ** i for i in range(8)]
    result = R.shrunk_growth_volatility(steady)
    assert result["observations"] == 7
    assert result["sampleSd"] == pytest.approx(0.0, abs=1e-9)
    assert result["sd"] < R.PRIOR_GROWTH_SD


def test_a_volatile_company_widens_it():
    erratic = [100.0, 180.0, 90.0, 200.0, 70.0, 210.0]
    stable = [100 * 1.05 ** i for i in range(6)]
    assert (R.shrunk_growth_volatility(erratic)["sd"]
            > R.shrunk_growth_volatility(stable)["sd"])


def test_shrinkage_never_lets_three_points_dominate():
    """The whole point: a tiny sample cannot swing the answer far."""
    result = R.shrunk_growth_volatility([100.0, 101.0, 102.0, 103.0])
    assert result["observations"] == 3
    assert result["priorWeight"] > 0.6
    # Sample says ~0 dispersion; the answer must stay meaningfully above zero.
    assert result["sd"] > R.PRIOR_GROWTH_SD * 0.6


def test_sigma_is_for_the_horizon_average_not_one_year():
    """The units error that would inflate every fan chart by ~10x.

    The Monte Carlo applies ONE growth draw across all five years, so the
    dispersion it needs is that of the five-year average, which is strictly
    narrower than the year-to-year scatter.
    """
    erratic = [100.0, 130.0, 95.0, 140.0, 90.0, 150.0, 100.0]
    result = R.shrunk_growth_volatility(erratic)

    assert result["predictiveSd"] < result["sampleSd"], (
        "predictive sd must be below the raw annual scatter"
    )
    expected = result["sampleSd"] * np.sqrt(1 / result["observations"] + 1 / result["horizon"])
    assert result["predictiveSd"] == pytest.approx(expected, rel=1e-9)
    assert result["sd"] < result["sampleSd"]


def test_sigma_stays_in_a_plausible_range_for_a_real_company():
    """A blue chip's calibrated sigma should land in single-digit percent, not 20%."""
    apple_like_fcf = [92.9e9, 111.4e9, 99.6e9, 108.8e9, 98.8e9]
    result = R.shrunk_growth_volatility(apple_like_fcf)
    assert 0.02 < result["sd"] < 0.12, result


def test_sign_changes_are_dropped_not_propagated():
    """FCF crossing zero yields nonsense growth rates; they must not count."""
    result = R.shrunk_growth_volatility([100.0, -50.0, 80.0, 120.0])
    assert result["skipped"] == 2
    assert np.isfinite(result["sd"])
    assert result["sd"] < 10.0
